### ISSUE TITLE
env_params attribute to obscure passwords in TeamCity web interface

### ISSUE THREAD

**Issue by tewing** [cvbarros/terraform-provider-teamcity#106]
Is it possible to set attributes on project env_settings in order to hide the value within the TeamCity WebUI?  When I define a teamcity project in Kotlin DSL I can define it as a password field but  I don't see a way to do this in the terraform provider.  

In the terraform example below, I would like the AWS_SECRET_ACCESS_KEY to be obscured in the TeamCity web interface.

**Kotlin example:**
```
project {
    params {
        password("env.AWS_SECRET_ACCESS_KEY", "credentialsJSON:99999ae8-b477-4411-980d-4a99999ef")
        text("env.AWS_ACCESS_KEY_ID", "ZZZZZZZZZZZZ", allowEmpty = true)
        param("env.AWS_DEFAULT_REGION", "us-west-2")
    }
}
```

**Terraform example:**
```
resource "teamcity_project" "project1" {
  name        = "Project1"
  env_params = {
    AWS_SECRET_ACCESS_KEY = "xxxxxxxx" # <-- Need to define this as a password field
    AWS_ACCESS_KEY_ID = "ZZZZZZZZZ"
    AWS_DEFAULT_REGION = "us-west-2"
  }
}
```

**Comment by cvbarros** [comment]
Not yet, this need a wider implementation from https://github.com/cvbarros/go-teamcity/issues/38 client
