### ISSUE TITLE
Allow Build Template Associations on Build Configuration Resource

### ISSUE THREAD

**Issue by cvbarros** [cvbarros/terraform-provider-teamcity#26]
Make it possible to associate build configuration templates to a build configuration.

```hcl
resource "teamcity_build_config" "build1" {
   //Other properties

   //Build Templates are optional.
   //The order they are specified is the other they will be attached 
   //to the build configuration. It matters for parameter and inheritance precedence. 
   //This is a list of build template IDs to associate
   templates = ["Project_BuildTemplate1", "Project_BuildTemplate2"]
}
```

**Comment by TimPietrusky** [comment]
@cvbarros Is there any chance that this will be part of the provider anytime soon? Or do you need some support on this one?

**Comment by cvbarros** [comment]
Hey @TimPietrusky , if you want to give it a spin, go for it!
If not, I can definitely implement it in ~ 1 week timeframe or so. 

That shouldn't be too hard, since there is support for it in the client library 👍

**Comment by TimPietrusky** [comment]
@cvbarros if you have the time to actually do it, then I would love to use it of course! If not then I have to learn some go :D
