### ISSUE TITLE
When Project is created, the project ID does not take into account the namespace of the project

### ISSUE THREAD

**Issue by MattHodge** [cvbarros/terraform-provider-teamcity#32]
When creating a project, the `Project ID` field in TeamCity is given the same name as the project, ignoring the namespace/hierarchy that the project lives in.

For example, creating a sub-project with the name `Vault` under the following namespace `<Root Project> / .NET / net-deploy-example`:

* Created Project ID: `Vault`

* Expected Project ID: `Net_NetDeployExample_Vault`

**Comment by cvbarros** [comment]
Confirmed provider bug with the following configuration:

```
resource "teamcity_project" "parent" {
	name = "parent"
}

resource "teamcity_project" "child" {
	name = "child"
	parent_id = "${teamcity_project.parent.id}"
}

resource teamcity_build_config "build_config" {
	name = "build config"
	project_id = "${teamcity_project.child.id}"
}
```

Expected build config to have id: `Parent_Child_BuildConfig` but got `Child_BuildConfig` instead.
