### ISSUE TITLE
Incorrect build trigger vcs option documentation 

### ISSUE THREAD

**Issue by ss-remygreinhofer** [cvbarros/terraform-provider-teamcity#47]
In https://github.com/cvbarros/terraform-provider-teamcity/blob/master/website/r/build_trigger_vcs.html.md, the `rules` argument is marked as `Optional`, but is defined as required in the code: https://github.com/cvbarros/terraform-provider-teamcity/blob/master/teamcity/resource_build_trigger_vcs.go#L27

Provider Version: built from dffdff4 on master

**Comment by cvbarros** [comment]
Resolved via https://github.com/cvbarros/terraform-provider-teamcity/commit/c78f0b77e72f4fcc332dc748c7c19d9aa7358630
