### ISSUE TITLE
teamcity_vcs_root_git with branches is a multiline string but requires a list

### ISSUE THREAD

**Issue by Andor** [cvbarros/terraform-provider-teamcity#50]
Hello! I have a `teamcity_vcs_root_git` with customized `branches` via Teamcity UI and it's set to two-line string:
```
+:refs/heads/*
-:refs/heads/*-ng-build
```
And `Username style` is set to `Author Email` in the UI.

If I will specify branches in terraform code as list it will show be the plan:
```
  branches = [
    "+:refs/heads/*",
    "-:refs/heads/*-ng-build",
  ]
```
plan:
```
      branches.#:     "1" => "2"
      branches.0:     "+:refs/heads/*\n-:refs/heads/*-ng-build" => "+:refs/heads/*"
      branches.1:     "" => "-:refs/heads/*-ng-build"
      username_style: "" => "author_email"
```

**Comment by cvbarros** [comment]
@Andor did you import the resource before doing the plan?

**Comment by Andor** [comment]
@cvbarros sure I import it, this is why I have diff there.

**Comment by cvbarros** [comment]
@Andor I was finally able to reproduce this issue by manually debugging and looking at the TeamCity UI.
https://github.com/cvbarros/go-teamcity/commit/36ce0a2f3c13ea1262f14f1a62099c3d599010cd will fix it, and I'll update the upstream SDK to the provider will be fixed.
