### ISSUE TITLE
Release 12.X support

### ISSUE THREAD

**Issue by jspenc72** [cvbarros/terraform-provider-teamcity#53]
@cvbarros Can you create a release with 12.x support that was recently merged in?

**Comment by jspenc72** [comment]
#51 #52

**Comment by cvbarros** [comment]
I will as soon as I finish work being done in https://github.com/cvbarros/go-teamcity/pull/64
I'm converting the client SDK to go modules, cleaning up and renaming the project.

There will be breaking changes for the provider, at this point I'll release `v0.5.0`, including with precompiled binaries for ease of installation with goreleaser.

I'll also introduce a proper changelog. Just please hold a bit more in there and it will be done in no time 🙇 .
If in a rush, you can always build from source with current master 👍

**Comment by cvbarros** [comment]
@jspenc72 done: https://github.com/cvbarros/terraform-provider-teamcity/releases/tag/v0.5.0

**Comment by jspenc72** [comment]
Thank you!!!

**Comment by lmayorga1980** [comment]
can't wait for 0.12.x support.

**Comment by cvbarros** [comment]
@lmayorga1980 this has already been released
https://github.com/cvbarros/terraform-provider-teamcity/releases/tag/v0.5.0

**Comment by lmayorga1980** [comment]
Working on the terraform 0.12.x version and will provide more examples https://github.com/cvbarros/terraform-provider-teamcity/pull/62
