### ISSUE TITLE
Publish provider at registry.terraform.io

### ISSUE THREAD

**Issue by GennadySpb** [cvbarros/terraform-provider-teamcity#98]
Please consider publishing your provider at https://www.terraform.io/docs/registry/providers/publishing.html
Right now Hashicorp support publishing any provider. Checkout this [doc](https://www.terraform.io/docs/registry/providers/publishing.html).

**Comment by cvbarros** [comment]
Yup, I've seen that! I have a task for follow up on this by this Friday - latest beginning next week 👍 
Thanks for the heads-up!
